[package]
name = "netlist"
version = "0.1.0"
authors = ["Eric Hsu <xuzhenyutc@icloud.com>"]
edition = "2018"
descriptions = ["generic netlist data structure for VLSI design"]
exclude = [
    "testcases/*",
    "tests/*",
    "examples/*"
]

[dependencies]
nom = "6.0"
thiserror = "1.0"