name: rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1.0.1
      - name: rust test
        run: cargo test parse_verilog
      - name: rust build
        run: cargo build
