name: rust
on:
  push:
    branches: [ main ]
    paths_ignore: "README.md"
  pull_request:
    branches: [ main ]
jobs:
  build_and_test:
    name: rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - run: cargo test parse_verilog
      